version: "3.8"

services:
  app:
    image: rr:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - DB_NAME=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/1
    links:
      - redis
      - db
    depends_on:
      - db
      - redis
    ports:
      - 3000:3000

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec sidekiq
    environment:
      - DB_NAME=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/1
    links:
      - redis
      - db
    depends_on:
      - db
      - redis

  redis:
    image: redis:latest

volumes:
  gem_cache:
  db_data:
