default: &default
  # adapter: postgresql
  adapter: sqlite3
  encoding: unicode
  # username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  # password: <%= ENV.fetch("DB_PASSWORD", "postgres") %>
  # host: <%= ENV.fetch("DB_HOST", "localhost") %>
  # port: <%= ENV.fetch("DB_PORT", "5432") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  # database: <%= ENV.fetch("DB_NAME", "rupee_rally_dev") %>
  database: db/development.sqlite3

test:
  <<: *default
  # database: <%= ENV.fetch("DB_NAME", "rupee_rally_dev_test") %>
  database: db/test.sqlite3

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "rupee_rally_dev_prod") %>
  database: db/production.sqlite3
