name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
    secrets:
      docker_username:
        required: true
      docker_password:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}

      - name: Set up QEMU for multi-platform builds
        uses: docker/setup-buildx-action@v2

      - name: Build and Tag Docker image
        id: build_image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ inputs.image_name }}:latest
            ${{ inputs.image_name }}:${{ github.sha }}
            ${{ inputs.image_name }}:${{ github.ref_name }}
